### ISSUE TITLE
pluma libspell.so

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#10]
Failed to load module 'spell': /usr/lib/pluma/plugins/libspell.so: undefined symbol: enchant_dict_add_to_pwl

**Comment by attuska** [comment]
Megoldva, Manjaro már megcsinálta.
https://github.com/uhulinux/ub-ubk3/commit/baf907a5a908ba8b29d8f9be0a50bd64125fa914

**Comment by rezso** [comment]
A patch-nak amúgy azért sincs értelme, mert enchant_dict_add_to_pwl eleve nincs az enchant 2-ben. Csak épp az ld nem fut hibára emiatt valamiért.
