### ISSUE TITLE
blueman hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#114]
Jó mindene, csak a blueman-applet parancs így végzi:
>  File "/usr/lib/python3.7/site-packages/blueman/plugins/applet/AppIndicator.py", line 13, in <module>
    raise ImportError("AppIndicator3 not found")
ImportError: AppIndicator3 not found
blueman-applet 17.20.12 WARNING  PluginManager:147 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 17.20.12 WARNING  PluginManager:147 __load_plugin: Not loading DhcpClient because its conflict has higher priority

**Comment by rezso** [comment]
https://github.com/blueman-project/blueman/commit/0c3596c2ecf25d0786ab424c1eaf0478d42c162b

**Comment by attuska** [comment]
Kösz a linket, némi javulást hozott, legalábbis nem áll meg már.
https://github.com/uhulinux/ub-ubk3/commit/968a724ccf38bb83bef4c54b566e711ac2f44e7d
