### ISSUE TITLE
mate-control-center, ftmenu giant icons

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#15]
Hasonló UBK1 issue: https://github.com/uhulinux/ub-ubk1/issues/23
UBK3/xfce menu kép ilyen:

![xfcemenu](https://user-images.githubusercontent.com/6311614/46570311-5a136a80-c962-11e8-9ea4-b5291ccdc99e.png)

Ez senkinek nem fog tetszeni!
GTK bug?

**Comment by attuska** [comment]
Mintha ez a https://github.com/uhulinux/ub-ubk3/commit/1486cdab133d54113c5fa630f48acc8b69dcfd10 commit még kevés lenne.
Lehet, hogy ez is kellene, hogy rendbejöjjön:
https://aur.archlinux.org/packages/glib2-patched-thumbnailer/

Se az újraforgatott ftmenu, sem az xfce nem jó még.

**Comment by attuska** [comment]
UBK1 alatt jó és egységes a menü ikonmérete, UBK2 alatt már nem egységes méretű, de még elviselhető, UBK3 alatt már katasztofális.
UBK1 alatt már az ftmenu ikonmérete is akatasztrofálisan változó nagyságú és mindhárom disztrónál ócska.

**Comment by attuska** [comment]
A nautilus az egyetlen igazi óriási ikon az új fvwm xdg generált menüjében is.
Ha ez a nautilus ki lenne javítva, máris elviselhetőbb lenne minden xdg menügenerátor által létrehozott menü.

**Comment by attuska** [comment]
> attila@attila-pc:/usr/src/UHUBUILD/UB-UBK3$ zgrep org.gnome.Nautilus Contents.gz
nautilus:   0   0  f  644    16164 /usr/share/applications/org.gnome.Nautilus.desktop
nautilus:   0   0  f  644       86 /usr/share/dbus-1/services/org.gnome.Nautilus.service
nautilus:   0   0  f  644      144 /usr/share/gnome-shell/search-providers/org.gnome.Nautilus.search-provider.ini
nautilus:   0   0  f  644    53705 /usr/share/icons/hicolor/16x16/apps/org.gnome.Nautilus.png
nautilus:   0   0  f  644    53705 /usr/share/icons/hicolor/22x22/apps/org.gnome.Nautilus.png
nautilus:   0   0  f  644    53705 /usr/share/icons/hicolor/24x24/apps/org.gnome.Nautilus.png
nautilus:   0   0  f  644    53705 /usr/share/icons/hicolor/32x32/apps/org.gnome.Nautilus.png
nautilus:   0   0  f  644    53705 /usr/share/icons/hicolor/48x48/apps/org.gnome.Nautilus.png
nautilus:   0   0  f  644    53705 /usr/share/icons/hicolor/512x512/apps/org.gnome.Nautilus.png
nautilus:   0   0  f  644     4072 /usr/share/icons/hicolor/symbolic/apps/org.gnome.Nautilus-symbolic.svg
nautilus:   0   0  f  644    69538 /usr/share/metainfo/org.gnome.Nautilus.appdata.xml
attila@attila-pc:/usr/src/UHUBUILD/UB-UBK3$ 

Nekem gyanús ez az 512x512 pixel nagyságú ikon!

**Comment by attuska** [comment]
Lehet, hogy ez a kommit valamit javított, mert valamivel kisebbek lettek a menü ikonjai, de még mindig nem egységes méretű. Függ az ikonkészket beállításától is.
https://github.com/uhulinux/ub-ubk3/commit/8f7e7c3f51d5909b17f74aac6b3a2bfc6b54f308

**Comment by attuska** [comment]
A mate-control-center -ben is megfigyelhető, hogy nem egyformák az ikonok.
Nálam kettő van, amelyik nagyobb a többinél, az Elementary Configuration ikonja és az obconf-qt ikonja.

![mate-control-center1](https://user-images.githubusercontent.com/6311614/47961672-c8098b00-e00f-11e8-87f5-5e10a353bff1.png)

Valami más is lehet a dologban, nem csak a gtk2.

**Comment by attuska** [comment]
Az xfce asztaljára kattinva az egér jobbszemével, a felbukkanó menü jó és egységes méretű ikonokat tartalmaz, csak a panel alaklmazásmenüje a hibás.
A wiskesmenu plugin menüje is rendben van.

**Comment by attuska** [comment]
Az elementary configuration ikonja továbbra is órási a mate beállítóközpontban.

**Comment by rezso** [comment]
A frissített efl csomaggal jó?

**Comment by attuska** [comment]
Az efl jó lett! Csak az obconf-qt ikonja nagyobb, de az annyira nem kirívó. Az ftmenu -t még nem néztem.
