### ISSUE TITLE
cinnamon-settings python hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#18]
Nem indul.
>attila@attila-pc:~$ cinnamon-settings
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:217: DeprecationWarning: Gtk.Widget.set_margin_right is deprecated
  self.stack_switcher.set_margin_right(n)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:230: DeprecationWarning: Gtk.Window.set_has_resize_grip is deprecated
  self.window.set_has_resize_grip(False)
/usr/lib/python3.7/site-packages/PIL/Image.py:86: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 5.3.0
Pillow version: 5.2.0
  warnings.warn(str(v), RuntimeWarning)
The _imaging extension was built for another version of Pillow or PIL:
Core version: 5.3.0
Pillow version: 5.2.0
attila@attila-pc:~$

**Comment by rezso** [comment]
Valószínűleg még fent van az előző, 5.2.0-s python3-pillow is. Új telepítéssel érdemes megpróbálni.

**Comment by attuska** [comment]
A python-pillow újraforgatása és ennek feltelepítése volt a megoldás.
