### ISSUE TITLE
twm not starting,  ("-adobe-helvetica-bold-r-normal---120------*" font is missing?)

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#19]
~/.local/share/sddm/xorg-session.log:
**unable to open fontset "-adobe-helvetica-bold-r-normal--*-120-*-*-*-*-*-*"**

Csak kilőni lehet az ssdm-et, egér nem reagál semmire sem.
UBK2 -n megy ez a rettenetes twm...

**Comment by attuska** [comment]
UTF gond lehet.
https://bugzilla.redhat.com/show_bug.cgi?id=509639

**Comment by rezso** [comment]
fonts-x.org-iso csomagok valamelyike fent van?
Pl. fonts-x.org-iso-10646 vagy fonts-x.org-iso-8859-1

**Comment by attuska** [comment]
Igen, A base, 10646, 8859.1, 8859-2, other, ttf, type1 van fenn.
Olyan alapvető ez a twm, hogy kidobni szerintem emiatt nem szabad, habár a kutya sem használja.

**Comment by attuska** [comment]
A /usr/share/fonts/fonts.dir.-iso-8859-2 fájlban van egy ilyen sor:

helvB12-ISO8859-2.pcf -adobe-helvetica-bold-r-normal--17-120-100-100-p-92-iso8859-2

UBK2-n is.

**Comment by attuska** [comment]
A twm forrásában a src/util.c GetFont() funciójában szerepel ez a sszakasz, amely a hibaüzenetet kiírja és kilép:
>    if (use_fontset) {
	if (font->fontset != NULL){
	    XFreeFontSet(dpy, font->fontset);
	}
>
>	if( (font->fontset = XCreateFontSet(dpy, font->name,
					    &missing_charset_list_return,
					    &missing_charset_count_return,
					    &def_string_return)) == NULL) {
	    fprintf (stderr, "%s:  unable to open fontset \"%s\"\n",
			 ProgramName, font->name);
	    exit(1);
	}:

Kérdés, hogy, ez miért nem leli?

**Comment by attuska** [comment]
x.org-server hiba volt.
https://github.com/uhulinux/ub-ubk3/commit/53b9c7ab49357be358d6b0d670b8c47f48069f31
