### ISSUE TITLE
frogatto-data csomag egybeolvasztása a frogatto csomaggal.

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#29]
A csomag postints -je nem működik, a githubos forrásból a letöltés mindig megszakad, azáltal a data csomag hiányosan települ.
A külön frogatto-data csomagnak így semmi értelme, mert a letöltendő mennyiség mérete abnormálisan nagy és nem minden internernet kapcsolat és gépösszeállítás esetém működőképes.

**Comment by rezso** [comment]
https://github.com/uhulinux/ub-ubk3/commit/2e7681a40f6b31b24a686b386e2cb48bbe225f8d
