### ISSUE TITLE
accerciser ipython_view.py hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#38]
>attila@attila-pc:/usr/share/applications$ /usr/bin/accerciser
/usr/bin/accerciser:52: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
Traceback (most recent call last):
  File "/usr/bin/accerciser", line 78, in <module>
    accerciser.main()
  File "/usr/lib/python3.7/site-packages/accerciser/__init__.py", line 34, in main
    from .accerciser import Main
  File "/usr/lib/python3.7/site-packages/accerciser/accerciser.py", line 106
    pyatspi.Registry.start(async=True, gil=False)
                               ^
SyntaxError: invalid syntax
attila@attila-pc:/usr/share/applications$

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk3/commit/3cb81c395ee3f1d088a70f95d36239e608d9927a

Már nem failed, elindul, mert a python-3.7 volt neki sok, az upstream már adaptálta a foltot az accessiser nem stable ágában.

Ellnben az Ipython-t nem leli, még a legfrissebb Ipithont sem a legfrissebb gitből letöltött accessiser sem.
Ezt még senki nem reklamálta a világhálón, ez a bővítményhiba ablakban jelenik meg.

>RuntimeError: The IPython module is required for the IPython console
>Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/accerciser/plugin/plugin_manager.py", line 140, in _getPluginLocals
    plugin = imp.load_module(plugin_fn, *params)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/accerciser/plugins/console.py", line 25, in <module>
    raise RuntimeError('The IPython module is required for the IPython console')
RuntimeError: The IPython module is required for the IPython console

**Comment by attuska** [comment]
Ennek az IPython -nak kell még egy rakás nálunk még nem létező python modul.

Eddig ezeket csináltam meg, de még mindig nem elég:

backcall
pickleshare
prompt-toolkit
traitlets
wcwidth

Most még kellene a simplegeneric, de mára belefáradtam.

**Comment by rezso** [comment]
Megnéztem ubk2 alatt. Nem teljesen világos, hogy mire jó, ráadásul egy rakás dologra azt írta, hogy „nincs megvalósítva”.
Szóval én leginkább kidobnám az accerciser-t, úgy, ahogy van.

**Comment by attuska** [comment]
Én a kidobással inkább még várnék, nem véletlen van ez benne a gnome alap készletében.
Igaz, a gnome-sotware is ott csúnyálkodik, de csak nálunk csúnya, a "nagy" disztrókhoz mind igazítva lett, csak hát mi kicsik vagyunk, velünk nem foglalkoznak.
Ahelyett viszont van még 2 működő szoftverkarbantartó alternatíva, az accerciser helyett meg nincs más egyelőre.

**Comment by attuska** [comment]
A simplegeneric csomagot felrakva betöltődik az IPython, ámde:

>  File "/usr/lib/python3.7/site-packages/accerciser/plugin/plugin_manager.py", line 192, in _enablePlugin
    plugin_instance.init()
  File "/usr/share/accerciser/plugins/console.py", line 42, in init
    self.ipython_view = ipython_view.IPythonView()
  File "/usr/share/accerciser/plugins/ipython_view.py", line 549, in __init__
    input_func=self.raw_input)
  File "/usr/share/accerciser/plugins/ipython_view.py", line 128, in __init__
    self.IP.readline_startup_hook(self.IP.pre_readline)
AttributeError: 'InteractiveShellEmbed' object has no attribute 'readline_startup_hook'

**Óh, be nagy öröm!**

**Comment by attuska** [comment]
Találtam egy foltot a gnome gitlabon erre, ezt alkalmazva már továbblódul és jön az újabb:

>Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/accerciser/plugin/plugin_manager.py", line 192, in _enablePlugin
    plugin_instance.init()
  File "/usr/share/accerciser/plugins/console.py", line 42, in init
    self.ipython_view = ipython_view.IPythonView()
  File "/usr/share/accerciser/plugins/ipython_view.py", line 556, in __init__
    self.execute()
  File "/usr/share/accerciser/plugins/ipython_view.py", line 175, in execute
    self.IP.input_splitter.push(line)
AttributeError: 'TransformerManager' object has no attribute 'push'

**Miért nem adnak ki újabb release -t a gnómosok?**

**Comment by attuska** [comment]
Az accessiser dev-release (3.31.4) is a fenti hibát produkálja (a FEDORA gittje alapján csináltam), vagyis nem lett még kijavítva a gnome gittben.

**Comment by attuska** [comment]
Ez a végső, de még nem teljes stádium:
https://github.com/uhulinux/ub-ubk3/commit/d2fcdfc1fda34157aafc76aa26067f6912ca2bef
A PyGIWarning az elején is kifoltozva, de lett helyette egy újabb IPython warning:
>/usr/lib/python3.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)


Már csak a https://github.com/uhulinux/ub-ubk3/issues/38#issuecomment-455849258 commentben jelzett hiba maradt csak meg,

Részemről ennyi, várjunk a fejlesztőkre!

**Comment by attuska** [comment]
túlhaladott
