### ISSUE TITLE
/etc/pam.d/graphic-login ???

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#52]
Nevezett a pam feltelepítése után eltűnik, a csomagban van, de a telepítményből az uhu-pkg törli!

**Comment by attuska** [comment]
A csomagból mc-vel bemásolva a graphic.login -t, ez, a graphic-login a pam csomag újratelepítése után már nem törlődik.
Tehát, ha valami, vagy valaki szándékosan, vagy véletlenül törli nevezett fájlt, a pam csomag újratelepítése nem telepíti már!
Ez bizony csomagtelepítési szarvashiba!

**Comment by rezso** [comment]
Az uhu-pkg biztosan nem törli.

**Comment by attuska** [comment]
Nem az a kérdés, hogy ki, vagy mi törölte.
Miért nem települ a csomag újratelepítésekor a konfigurációs fájl, ha előzőleg valaki/valami akarva/akaratlanul törölte?

A pam conffiles fájljában most ez van:
>/etc/pam.d/deny-all
/etc/pam.d/graphic-login
/etc/pam.d/only-root
/etc/pam.d/permit-all
/etc/pam.d/system-auth
/etc/pam.d/system-auth-rootok
/etc/security/access.conf
/etc/security/group.conf
/etc/security/limits.conf
/etc/security/pam_env.conf
/etc/security/time.conf

Ebben szerepel a nevezett graphic-login.

**Ezért írtam, hogy ez egy csomagtelepítési szarvashiba!**

Nyilvan a hiba ott keresendő, ahol ennek a conffiles fájltnak feldolgozása/értelmezése zajlik.
