### ISSUE TITLE
tkffmpeg nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#71]
>attila@attila-pc:~$ tkffmpeg
Error in startup script: can't find package img::png
    while executing
"package require img::png"
    (file "/bin/tkffmpeg" line 14)
attila@attila-pc:~$

**Comment by rezso** [comment]
https://sourceforge.net/projects/tkimg/

**Comment by attuska** [comment]
A tkimg csomag elkészítés és feltelepítés után:
>attila@attila-pc:~$ tkffmpeg
tkffmpeg - frontend for ffmpeg
   Wasiliy Filippov 2010
   Motsyo Gennadi 2010
 tkffmpeg comes with ABSOLUTELY NO WARRANTY; for details read license.
 This is free software, and you are welcome to redistribute it
 under certain conditions.
 >
>Thank you for using our program
>
>Error in startup script: can't set "::tk::dialog::file::showHiddenBtn": parent namespace doesn't exist
    while executing
"set ::tk::dialog::file::showHiddenBtn 1"
    (file "/bin/tkffmpeg" line 790)
attila@attila-pc:~$

**Comment by attuska** [comment]
Gyanús, hogy ennek a tkffmpeg-nek már nem jó a mi tk-8.7a1 csomagunk, ARCH-Linuxnál is, mely rolling disztró, még csak tk-8.6.9.1 van.
Szerintem ki lehetne dobni egyelőre minden olyan csomagot, aminek a tk-8.7a1 nem jó, vagy visszafejleszteni a tk csomagot arra a verzióra, ami a tk cuccosoknak jó.
A tkffmpeg csomag más nincs is karbantartva, svn -ben van a forrása, az utolsó kommit 2015-04-29. Azóta nem nyúltak hozzá.
https://sourceforge.net/p/tkffmpeg/code/81/

**Comment by attuska** [comment]
UBK1, UBK2 nem indul, kapásból ezt írja:
>attila@attila-pc:~$ tkffmpeg
Error in startup script: can't find package img::png
    while executing
"package require img::png"
    (file "/usr/bin/tkffmpeg" line 14)
attila@attila-pc:~$
Senkinek nem hiányzott eddig az a tkffmpeg.

**Comment by attuska** [comment]
UBK1 alá elkészítve a tkimg csomagot és feltelepítve azt, a futáskori hibaüzenet ugyanaz, mint UBK3 -nál.
Tehát már az UBK1 -en lévő tk_8.6.5 is sok neki, vagy más egyéb baja lehet.

>Error in startup script: can't set "::tk::dialog::file::showHiddenBtn": parent namespace doesn't exist
while executing
"set ::tk::dialog::file::showHiddenBtn 1"
(file "/bin/tkffmpeg" line 790)

**Comment by attuska** [comment]
UBK3 kidobva!
https://github.com/uhulinux/ub-ubk3/commit/0c6868ca7aee7da150d1953fd2e59199185535de
