### ISSUE TITLE
ndisgtk not working

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#75]
>attila@attila-pc:~$ ndisgtk
  File "/proc/self/fd/6", line 47
    print "Failed to load GTK bindings. Please check your Gnome installation."
 >                                                                            ^
>SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed to load GTK bindings. Please check your Gnome installation.")?
attila@attila-pc:~$ 

Lehet, hogy ez a gnome2 -höz készült valaha?

**Comment by rezso** [comment]
Inkább python 2-höz. A python 3 ugyanis syntax error-t ad, ha a print nem zárójeles. Azaz python 3-ban a print "szöveg" hibát okoz, print("szöveg") a helyes forma.

**Comment by attuska** [comment]
Python2-re megfoltoztam.
Már csak a libgnome.so -t hiányolja, de attól még működik már.
https://github.com/uhulinux/ub-ubk3/commit/8d8e07e758c83164a7bdb84142d414cf8089f0f3
