### ISSUE TITLE
Programs with mesa nvidia nouveau OpenGL bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#80]
Több grafikus alkalmazás nem indul el a mesa opengl -el nvidia chippel.
A hiba az alábbi:

> libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

Ezek a hivatalos nvidia opengl -t tartalmazó nvidia csomagok feltelepítésével mind kifogástalanul mennek a mesa OpenGL rendszerével nem.

**Comment by attuska** [comment]
Az eddig talált alkalmazások, melyek nem, vagy hibásan működnek:
sweethome3d
![sweethome3d-nouveau](https://user-images.githubusercontent.com/6311614/68549689-52db4d80-03fb-11ea-95ff-4fec551e9ff3.jpg)
avogadro2
![avogadro2-nouveau](https://user-images.githubusercontent.com/6311614/68549716-933acb80-03fb-11ea-90cc-548aa5f5da5f.jpg)

hugin
>attila@attila-pc:~$ hugin
>
>(hugin:6610): Gtk-CRITICAL **: 18:40:06.757: gtk_widget_set_size_request: assertion 'height >= -1' failed
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
>
>(hugin:6610): Gdk-WARNING **: 18:40:07.265: The program 'hugin' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 391 error_code 158 request_code 152 (GLX) minor_code 6)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
attila@attila-pc:~$ 

limoo
>attila@attila-pc:~$ limoo
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
QGLXContext: Failed to create dummy context
QFSFileEngine::open: No file name specified
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Félbeszakítva (core készült)
attila@attila-pc:~$



google-earth
![google-earth](https://user-images.githubusercontent.com/6311614/68549755-10fed700-03fc-11ea-99f8-eabbf407733e.jpg)

**Comment by rezso** [comment]
nvidia chiphez nvidia driver való. Ha a nouveau nem kezeli jól az nvidia chipet, az nouveau probléma.
Viszont sosem lesz olyan jó, mint az eredeti gyári nviida driver, ez mindig egyértelmű volt.
Hol van itt a gond?

**Comment by attuska** [comment]
Tudom, egyértelmű, hogy a mesa nouveau OpenGL a nem megfelelő. Más OpenGL igényű játékoknál ellenben mind jó.
Alapvetően nyílt forású meghajtókkal kellene mindennek normálisan működnie.
Linux esetében nem bevett szokás hardwer drájverekre vadászni és telepíteni. A gyári Linux nvidia driver egyre másra dobja el a régebbi chipek támogatását és a mai napig nem képes normális wayland támogatást sem biztosítani. Nem jobb minden tekintetben a nyílt forrásúnál!  Ha a fentebb felsorolt alkalmazások más GPU -val normálisan működnek, akkor nvidia esetén miért nem működnek?
A mesa környékén kell kutakodni.

**Comment by attuska** [comment]
Módosítottam a mesa -t.
https://github.com/uhulinux/ub-ubk3/commit/cd76bc30d9aaba19137e45f6ad96db6a2ece8b49
A -Dgles2=true hatására már működik mindegyik a szabadforrású mesa meghajtókkal, kivéve a Google-earth nevűt, ez viszont GNOME wayland felületen jó a szabad forrásúval.
