### ISSUE TITLE
gpg --gen-key failure

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#94]
Gyors és nem teljes intaraktív módban nem érzékeli az O,o, Q,q gyorsbillentyűket, csak a Ctrl+c -vel lehet kilőni, ezért így nem lehet aláírási kulcsot generáltatni vele.
 
>attila@attila-pc:~$ gpg --gen-key
gpg (GnuPG) 2.2.17; Copyright (C) 2019 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
>
>Note: Use "gpg --full-generate-key" for a full featured key generation dialog.
>
>GnuPG needs to construct a user ID to identify your key.
>
>Teljes név: Attila
E-mail cím: attus@enterpriseforever.com
Ön a következő felhasználói azonosítót választotta:
    "Attila <attus@enterpriseforever.com>"
>
>Change (N)ame, (E)mail, or (O)kay/(Q)uit? O
Change (N)ame, (E)mail, or (O)kay/(Q)uit? o
Change (N)ame, (E)mail, or (O)kay/(Q)uit? Q
Change (N)ame, (E)mail, or (O)kay/(Q)uit? q
Change (N)ame, (E)mail, or (O)kay/(Q)uit?

**Comment by attuska** [comment]
Ja, a gpg a nagybetű és kisbetű ID-ben lévő különbséget nem veszi figyelmbe a kulcs törlésekor.
Először mindig az attila kulcsok törlődnek, az újabban létrehozott Attila kulcsok mind megmaradnak! Persze ezek is törölhetők a második menetben és így a kulcsok listája üres. Ezután lehet a tartalékban lévő attila.asc és attila-secret.asc kulcsokat importálni az eredeti állapot visszaállításához.

**Comment by attuska** [comment]
Ezt a választási lehetőség a g10/keygen.c fájlban található. Ebbe kell belerondítani, vagy rossz a nyelvi fordítás.

>            else if (full) {
>		answer = cpr_get("keygen.userid.cmd", fail?
>		  _("Change (N)ame, (C)omment, (E)mail or (Q)uit? ") :
>		  _("Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? "));
>		cpr_kill_prompt();
>            }
>            else {
>		answer = cpr_get("keygen.userid.cmd", fail?
>		  _("Change (N)ame, (E)mail, or (Q)uit? ") :
>		  _("Change (N)ame, (E)mail, or (O)kay/(Q)uit? "));

Ebben nem reagál az O és Q billentyűkre, ha a full () nem teljesül

**Comment by attuska** [comment]
A q, Q helyett k, vagy K billentyűre kilép.
Az O/o helyett R, vagy r billentyűre folytatódik.
Ez a po/hu.po fájl 5555/5556/5557. sorában van:

>msgid "Change (N)ame, (E)mail, or (O)kay/(Q)uit? "
msgstr ""
"(N)év, (M)egjegyzés, (E)-mail megváltoztatása vagy (R)endben/(K)ilépés? "

Szerintem a fordítás a megjelenítéskor nem érvényesül, mivel az msgstr=""
Ellenben a végrehajtás során már a billentyűknél a fordított érvényesül!

Szerintem a hu.po fájlt patkolni kell!

**Comment by attuska** [comment]
A hu.po patkolása nem megoldás, továbbra is angolul üzen és magyar billentyűket vár.

**Comment by rezso** [comment]
Pontosabban:

msgstr ""
"(N)év, (M)egjegyzés, (E)-mail megváltoztatása vagy (R)endben/(K)ilépés? "

Ez a több soros fordítás sajátossága. Az első sor msgid "", az alatta lévő sor a tényleges fordítás.
Más kérdés, hogy ez itt teljesen felesleges.
Azért nem érvényesül, mert nem stabil fordítás.

**Comment by attuska** [comment]
A hu.po fejléce:
>"Project-Id-Version: gnupg 1.2.5\n"
"Report-Msgid-Bugs-To: translations@gnupg.org\n"
"POT-Creation-Date: 2019-07-09 15:16+0200\n"
"PO-Revision-Date: 2004-06-19 21:53+0200\n"
"Last-Translator: Nagy Ferenc László <nfl@nfllab.com>\n"
"Language-Team: Hungarian <translation-team-hu@lists.sourceforge.net>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

Nem vagyok hajlandó lefordítani rendesen magyarra, egyrészt időigényes, másrészt nem vagyok otthon az angolban. Inkább kinyírom ezt az ősi fordítást, és marad az angol, amivel végre jó.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk3/commit/5cdf2807a1c83205d0608c4b86ff3116a1eb9562

**Comment by attuska** [comment]
Újranyitom az egészet, mert a hu.po kinyírása nem oldja meg az alapvető problémát! Ezt csak egy helyes és aktuális fordítási fájl tenné meg, mely az eredi fordító feladata lenne és nem egy csomagkészítőé!

**Comment by attuska** [comment]
A 2.21 -es verziónál már jó.

**Comment by attuska** [comment]
A gpg frissítése megoldotta. https://github.com/uhulinux/ub-ubk3/commit/f0fe2445a2c270229557a139752cc0121d036687
